### PR TITLE
add LoadConfigurationFromString

### PR DESCRIPTION
**Pull request by oliveagle**
support to config at runtime:

```javascript
l4g.LoadConfigurationFromString(`<logging>
<filter enabled="true">
     <tag>stdout</tag>
     <type>console</type>
     <!-- level is (:?FINEST|FINE|DEBUG|TRACE|INFO|WARNING|ERROR) -->
     <level>DEBUG</level>
</filter>
</logging>`)
```

### CODE REVIEW

**Comment by alecthomas** [comment]
Thank you, though it would probably be more flexible to refactor to add a `LoadConfigurationFromReader(io.Reader)`.

**Comment by oliveagle** [comment]
added `LoadConfigurationFromReader`, but have to remove those redundant `filename` arg.

**Comment by alecthomas** [comment]
It looks like this PR is has conflicts?

**Comment by oliveagle** [comment]
fixed conflict, unit test and tested in client project 

```bash
# go test .
ok      github.com/oliveagle/log4go     0.159s
# go run client.go probe
command: probe
[11:49:39 GMT 2015/01/24] [CRIT] (main.main:52) -------------------------------------------------
```

**Comment by alecthomas** [comment]
Unfortunately, this is unmaintained.

**Pull request closed without merging**
